# docker-compose.yml
version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:8000"
    environment:
      # ElastiCache Configuration
      CACHE_ENDPOINT: "cab432-a2-cache-n11837225.km2jzi.cfg.apse2.cache.amazonaws.com:11211"

      # Cognito Configuration
      COGNITO_USER_POOL_ID: "ap-southeast-2_LB7ZrgcGZ"
      COGNITO_APP_CLIENT_ID: "3fm7qdn8bakjjeotmq7hqmgdj2"
      
      # Points to the 'ollama' service below
      OLLAMA_HOST: "http://ollama:11434"
    networks:
      - app_net
    depends_on:
      - ollama # Ensures ollama starts before the backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://54.253.169.172:5000/api/v1"
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama # Explicitly naming the container
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_net
    restart: unless-stopped

# --- VOLUME DEFINITION ADDED ---
volumes:
  ollama_data:

networks:
  app_net:
    driver: bridge