# docker-compose.yml
version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:8000"
    environment:
      # ElastiCache Configuration
      CACHE_ENDPOINT: "cab432-a2-cache-n11837225.km2jzi.cfg.apse2.cache.amazonaws.com:11211"

      # Cognito Configuration
      COGNITO_USER_POOL_ID: "ap-southeast-2_LB7ZrgcGZ"
      COGNITO_APP_CLIENT_ID: "3fm7qdn8bakjjeotmq7hqmgdj2"
      
      # Add this line to tell the backend how to find Ollama
      OLLAMA_HOST: "http://host.docker.internal:11434"
      
    networks:
      - app_net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      REACT_APP_API_URL: "http://llm-app-n11837225.cab432.com:5000/api/v1" 
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
    driver: bridge