# docker-compose.yml
version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:8000"
    environment:
      # ElastiCache Configuration
      CACHE_ENDPOINT: "cab432-a2-cache-n11837225.km2jzi.cfg.apse2.cache.amazonaws.com:11211" # <-- PASTE YOUR ENDPOINT HERE

      # Cognito Configuration
      COGNITO_USER_POOL_ID: "ap-southeast-2_LB7ZrgcGZ"
      COGNITO_APP_CLIENT_ID: "3fm7qdn8bakjjeotmq7hqmgdj2"
      
    networks:
      - app_net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      REACT_APP_API_URL: "http://llm-app-n11837225.cab432.com:5000/api/v1" # <-- Use YOUR Route 53 domain
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_net
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  app_net:
    driver: bridge